export function getProducts(menCategoryId, womenCategoryId) {
  return [
    // MEN Products
    {
      name: 'Herren T-Shirt',
      desc: 'Bequemes Baumwoll-T-Shirt',
      brand: 'Nike',
      size: 'M',
      color: 'Schwarz',
      price: 45.99,
      stock: 50,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Nike_T-shirt_model_portrait_result_bcckjz.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Hoodie',
      desc: 'Warmer Hoodie',
      brand: 'Adidas',
      size: 'L',
      color: 'Schwarz',
      price: 80.99,
      stock: 40,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588296/Black_Adidas_hoodie_with_trefoil_logo_result_kli5lk.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Jeans',
      desc: 'Slim-Fit Jeans',
      brand: 'Levis',
      size: 'S',
      color: 'Blau',
      price: 100.99,
      stock: 35,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Slim_fit_Levi_s_in_natural_light_result_f1tyab.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Jacke',
      desc: 'Winterjacke',
      brand: 'Zara',
      size: 'XL',
      color: 'Schwarz',
      price: 120.99,
      stock: 40,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588296/Black_winter_puffer_jacket_with_details_result_qut4cq.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Sneaker',
      desc: 'Laufschuhe',
      brand: 'Puma',
      size: 'M',
      color: 'Weiß',
      price: 130.99,
      stock: 60,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Puma_men_s_running_shoes_in_focus_result_az0pyu.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Shorts',
      desc: 'Freizeitshorts',
      brand: 'H&M',
      size: 'S',
      color: 'Beige',
      price: 90.99,
      stock: 55,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588296/Beige_men_s_casual_shorts_flat_lay_result_y6r7y9.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Hemd',
      desc: 'Formelles Hemd',
      brand: 'Tommy Hilfiger',
      size: 'L',
      color: 'Weiß',
      price: 60.99,
      stock: 40,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Tommy_Hilfiger_white_dress_shirt_result_xb0tws.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Jogginghose',
      desc: 'Bequeme Hose',
      brand: 'Nike',
      size: 'XL',
      color: 'Grau',
      price: 50.99,
      stock: 65,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Heather_gray_Nike_sweatpants_with_logo_result_ddok3t.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Kappe',
      desc: 'Stylische Kappe',
      brand: 'New Era',
      size: 'L',
      color: 'Schwarz',
      price: 35.99,
      stock: 35,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588296/Classic_New_York_Yankees_cap_shot_result_ytuocy.webp',
      categoryId: menCategoryId,
    },
    {
      name: 'Herren Socken',
      desc: 'Sockenpackung',
      brand: 'Adidas',
      size: 'S',
      color: 'Weiß',
      price: 25.99,
      stock: 70,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588295/Adidas_sock_pack_in_neat_display_result_pul6ez.webp',
      categoryId: menCategoryId,
    },

    // WOMEN Products
    {
      name: 'Damen Kleid',
      desc: 'Sommerkleid',
      brand: 'Zara',
      size: 'M',
      color: 'Gelb',
      price: 60.99,
      stock: 35,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588817/Floral_summer_dress_from_Zara_result_fsexa4.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Rock',
      desc: 'Freizeitrock',
      brand: 'H&M',
      size: 'L',
      color: 'Beige',
      price: 45.99,
      stock: 60,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588818/Beige_A-line_mini_skirt_flat_lay_result_ze01lf.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Bluse',
      desc: 'Elegante Bluse',
      brand: 'Mango',
      size: 'S',
      color: 'Weiß',
      price: 55.99,
      stock: 45,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588819/Elegant_white_blouse_with_bow_detail_result_u05cyz.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Jeans',
      desc: 'High-Waist Jeans',
      brand: 'Levis',
      size: 'L',
      color: 'Blau',
      price: 70.99,
      stock: 35,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588818/Classic_light_blue_Levi_s_jeans_flat_lay_result_vo5f5w.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Jacke',
      desc: 'Lederjacke',
      brand: 'Zara',
      size: 'M',
      color: 'Schwarz',
      price: 85.99,
      stock: 25,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588818/Black_leather_biker_jacket_display_result_ibwzv7.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen High Heels',
      desc: 'Hohe Absätze',
      brand: 'Gucci',
      size: 'M',
      color: 'Schwarz',
      price: 150.99,
      stock: 15,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588817/Gucci_black_suede_high_heels_result_pj8u18.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Sneaker',
      desc: 'Sportschuhe',
      brand: 'Nike',
      size: 'XL',
      color: 'Weiß',
      price: 95.99,
      stock: 50,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588817/Nike_Air_Force_1_in_beige_accents_result_b2rqy6.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Handtasche',
      desc: 'Luxustasche',
      brand: 'Prada',
      size: 'M',
      color: 'Schwarz',
      price: 200.99,
      stock: 30,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588817/Prada_black_quilted_leather_shoulder_bag_result_dyqgil.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen T-Shirt',
      desc: 'Basic T-Shirt',
      brand: 'Adidas',
      size: 'S',
      color: 'Grau',
      price: 35.99,
      stock: 65,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588818/Adidas_T-shirt_in_heather_gray_result_lpiiq8.webp',
      categoryId: womenCategoryId,
    },
    {
      name: 'Damen Leggings',
      desc: 'Stretch-Leggings',
      brand: 'Puma',
      size: 'L',
      color: 'Pink',
      price: 55.99,
      stock: 75,
      imageUrl:
        'https://res.cloudinary.com/dwtme9i7k/image/upload/q_auto/f_auto/v1775588817/Mauve_Puma_leggings_with_logo_result_k1ytmg.webp',
      categoryId: womenCategoryId,
    },
  ];
}
